name: Reusable workflow

on:
  workflow_call:
    inputs: 
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World

jobs:
  Reusable-Job:
    runs-on: ubuntu-latest
    name: reusable-job
    steps:
      - run: echo "Hello ${{ inputs.who-to-greet }}"
        name: echo
